// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/security.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecurityRequest carries the command-line arguments that should be forwarded
// to the macOS `security` CLI.
type SecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequest) Reset() {
	*x = SecurityRequest{}
	mi := &file_proto_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequest) ProtoMessage() {}

func (x *SecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequest.ProtoReflect.Descriptor instead.
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// SecurityResponse carries the output produced by the macOS `security` CLI.
type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_proto_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_proto_security_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SecurityResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SecurityResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_security_proto protoreflect.FileDescriptor

const file_proto_security_proto_rawDesc = "" +
	"\n" +
	"\x14proto/security.proto\x12\bsecurity\"%\n" +
	"\x0fSecurityRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"_\n" +
	"\x10SecurityResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCodeB7Z5github.com/cprimera/container-security/internal/protob\x06proto3"

var (
	file_proto_security_proto_rawDescOnce sync.Once
	file_proto_security_proto_rawDescData []byte
)

func file_proto_security_proto_rawDescGZIP() []byte {
	file_proto_security_proto_rawDescOnce.Do(func() {
		file_proto_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)))
	})
	return file_proto_security_proto_rawDescData
}

var file_proto_security_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_security_proto_goTypes = []any{
	(*SecurityRequest)(nil),  // 0: security.SecurityRequest
	(*SecurityResponse)(nil), // 1: security.SecurityResponse
}
var file_proto_security_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_security_proto_init() }
func file_proto_security_proto_init() {
	if File_proto_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_security_proto_rawDesc), len(file_proto_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_security_proto_goTypes,
		DependencyIndexes: file_proto_security_proto_depIdxs,
		MessageInfos:      file_proto_security_proto_msgTypes,
	}.Build()
	File_proto_security_proto = out.File
	file_proto_security_proto_goTypes = nil
	file_proto_security_proto_depIdxs = nil
}
